
from d3x0r/node-alpine-gui as platform
label buildTools="Root Build(GUI) System"

RUN apk add python3 make gcc g++ cmake ninja gdb

RUN apk add git
RUN apk add nodejs npm

RUN apk add linux-headers
RUN apk add unixodbc-dev 
RUN apk add util-linux-dev
RUN apk add wayland-protocols wayland-dev libxkbcommon-dev glew-dev

RUN apk add ncurses-dev ncurses slang

